### ISSUE TITLE
HELP MEH !

### ISSUE THREAD

**Issue by ZEHNNNN** [goldentouch74/PiggyBookSystem#7]
Hello I Got Error On This Plugin Please Reply It I Really Need This Plugin COde Error ->
"Undefined property: goldentouch74\BookSystem\Main::$cofig" (EXCEPTION) in "plugins/PiggyBookSystem.phar/src/goldentouch74/BookSystem/Main" at line 86

**Comment by goldentouch74** [comment]
This project has been abandoned, Apologise.
