### ISSUE TITLE
/ceshop Not working

### ISSUE THREAD

**Issue by BroCrows** [goldentouch74/PiggyBookSystem#9]
18.09 00:34:40 [Server] Server thread/CRITICAL Error: "Call to a member function createSimpleForm() on null" (EXCEPTION) in "plugins/PiggyBookSystem_dev-14.phar/src/goldentouch74/BookSystem/Main" at line 37
18.09 00:34:40 [Server] Server thread/DEBUG #0 src/pocketmine/command/PluginCommand(58): goldentouch74\BookSystem\Main->onCommand(object pocketmine\Player, object pocketmine\command\PluginCommand, string[6] ceshop, array[0])
18.09 00:34:40 [Server] Server thread/DEBUG #1 src/pocketmine/command/SimpleCommandMap(270): pocketmine\command\PluginCommand->execute(object pocketmine\Player, string[6] ceshop, array[0])
18.09 00:34:40 [Server] Server thread/DEBUG #2 src/pocketmine/Server(2029): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[6] ceshop)
18.09 00:34:40 [Server] Server thread/DEBUG #3 src/pocketmine/Player(2231): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[6] ceshop)
18.09 00:34:40 [Server] Server thread/DEBUG #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(240): pocketmine\Player->chat(string[7] /ceshop)
18.09 00:34:40 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
18.09 00:34:40 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
18.09 00:34:40 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/protocol/BatchPacket(123): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
18.09 00:34:40 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
18.09 00:34:40 [Server] Server thread/DEBUG #9 src/pocketmine/Player(3126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
18.09 00:34:40 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
18.09 00:34:40 [Server] Server thread/DEBUG #11 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] 174.207.16.115 11701, object raklib\protocol\EncapsulatedPacket, integer 0)
18.09 00:34:40 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
18.09 00:34:40 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
18.09 00:34:40 [Server] Server thread/DEBUG #14 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
18.09 00:34:40 [Server] Server thread/DEBUG #15 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
18.09 00:34:40 [Server] Server thread/DEBUG #16 src/pocketmine/Server(2348): pocketmine\snooze\SleeperHandler->sleepUntil(double 1568766880.0218)
18.09 00:34:40 [Server] Server thread/DEBUG #17 src/pocketmine/Server(2205): pocketmine\Server->tickProcessor()
18.09 00:34:40 [Server] Server thread/DEBUG #18 src/pocketmine/Server(1784): pocketmine\Server->start()
18.09 00:34:40 [Server] Server thread/DEBUG #19 src/pocketmine/PocketMine(275): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /, string[55] /plugins/)
18.09 00:34:40 [Server] Server thread/DEBUG #20 src/pocketmine/PocketMine(299): pocketmine\server()
18.09 00:34:40 [Server] Server thread/DEBUG #21 (1): require(string[114] phar:///PMMP-1.12.0-Latest-Stable.)
18.09 00:34:40 [Server] Server thread/INFO ZZWILLIAMXX left the game
18.09 00:34:40 [Server] Server thread/INFO ZZWILLIAMXX[(IP)] logged out due to Internal server error
18.09 00:34:40 [Server] RakLibServer thread/NOTICE Blocked (IP) for 5

**Comment by Aericio** [comment]
I've fixed it in #8 and also added a download link to the phar.
